global using TopLearn.Core.DTOs;
global using TopLearn.Convertors;
global using TopLearn.Core.Convertors;
global using TopLearn.Core.Generator;
global using TopLearn.DataLayer.Entities.User;
global using TopLearn.DataLayer.Entities;
global using TopLearn.Core.Services.Interfaces;
global using TopLearn.DataLayer.Entities.Permissions;
global using TopLearn.Core.Security;